import type { Question } from "@/data/types";

export const higherMathsDifferentiationQuestions: Question[] = [
  {
    id: "hm-calc-diff-basic-f-001",
    subject: "Higher Maths",
    courseArea: "Calculus",
    specArea: "Differentiation",
    skillPath: "Basic differentiation",
    skillPathId: "basic-differentiation",
    stageId: "basic-diff-stage-foundations",
    stage: "Foundations",
    skill: "Power rule",
    title: "Differentiate a power",
    questionText: "Differentiate $f(x)=x^5$.",
    marks: 1,
    answerType: "algebraic",
    correctAnswer: "5x^4",
    acceptedAnswers: ["5x^4", "5*x^4", "5x^{4}"],
    workedSolution: "Use the power rule:\n\n$$\\frac{d}{dx}(x^n)=nx^{n-1}$$\n\nFor $x^5$, $n=5$, so:\n\n$$f'(x)=5x^4$$",
    finalAnswer: "$5x^4$",
    hint: "Bring the power down, then reduce the power by 1.",
    commonMistake: "A common mistake is writing $x^4$ and forgetting the coefficient 5.",
    calculatorAllowed: false,
    source: "Original STEM Forge question",
    status: "ready",
    displayOrder: 1,
  },
  {
    id: "hm-calc-diff-basic-f-002",
    subject: "Higher Maths",
    courseArea: "Calculus",
    specArea: "Differentiation",
    skillPath: "Basic differentiation",
    skillPathId: "basic-differentiation",
    stageId: "basic-diff-stage-foundations",
    stage: "Foundations",
    skill: "Differentiate sums",
    title: "Differentiate a sum of powers",
    questionText: "Differentiate $y=3x^4-2x^2+7$.",
    marks: 2,
    answerType: "algebraic",
    correctAnswer: "12x^3-4x",
    acceptedAnswers: ["12x^3-4x", "12*x^3-4*x", "12x^{3}-4x"],
    workedSolution: "Differentiate each term separately:\n\n$$\\frac{d}{dx}(3x^4)=12x^3$$\n\n$$\\frac{d}{dx}(-2x^2)=-4x$$\n\nThe derivative of a constant is 0.\n\n$$\\frac{dy}{dx}=12x^3-4x$$",
    finalAnswer: "$12x^3-4x$",
    hint: "Differentiate each term separately. Constants disappear.",
    commonMistake: "Students often keep the +7 in the derivative, but constants differentiate to 0.",
    calculatorAllowed: false,
    source: "Original STEM Forge question",
    status: "ready",
    displayOrder: 2,
  },
  {
    id: "hm-calc-diff-basic-f-003",
    subject: "Higher Maths",
    courseArea: "Calculus",
    specArea: "Differentiation",
    skillPath: "Basic differentiation",
    skillPathId: "basic-differentiation",
    stageId: "basic-diff-stage-foundations",
    stage: "Foundations",
    skill: "Evaluate derivative",
    title: "Evaluate a derivative",
    questionText: "For $f(x)=x^3+2x$, find $f'(2)$.",
    marks: 2,
    answerType: "numerical",
    correctAnswer: "14",
    acceptedAnswers: ["14"],
    workedSolution: "First differentiate:\n\n$$f'(x)=3x^2+2$$\n\nNow substitute $x=2$:\n\n$$f'(2)=3(2)^2+2=12+2=14$$",
    finalAnswer: "$14$",
    hint: "Find $f'(x)$ first, then substitute $x=2$.",
    commonMistake: "Some students substitute into $f(x)$ instead of $f'(x)$.",
    calculatorAllowed: false,
    source: "Original STEM Forge question",
    status: "ready",
    displayOrder: 3,
  },
  {
    id: "hm-calc-diff-basic-a-001",
    subject: "Higher Maths",
    courseArea: "Calculus",
    specArea: "Differentiation",
    skillPath: "Basic differentiation",
    skillPathId: "basic-differentiation",
    stageId: "basic-diff-stage-applications",
    stage: "Applications",
    skill: "Gradient of a curve",
    title: "Find gradient at a point",
    questionText: "The curve has equation $y=2x^3-x^2$. Find the gradient of the curve when $x=1$.",
    marks: 3,
    answerType: "numerical",
    correctAnswer: "4",
    acceptedAnswers: ["4"],
    workedSolution: "Differentiate the equation:\n\n$$\\frac{dy}{dx}=6x^2-2x$$\n\nSubstitute $x=1$:\n\n$$6(1)^2-2(1)=6-2=4$$",
    finalAnswer: "$4$",
    hint: "The gradient is found by evaluating $\\frac{dy}{dx}$.",
    commonMistake: "Students sometimes substitute into $y$ instead of into the derivative.",
    calculatorAllowed: false,
    source: "Original STEM Forge question",
    status: "ready",
    displayOrder: 4,
  },
  {
    id: "hm-calc-diff-basic-a-002",
    subject: "Higher Maths",
    courseArea: "Calculus",
    specArea: "Differentiation",
    skillPath: "Basic differentiation",
    skillPathId: "basic-differentiation",
    stageId: "basic-diff-stage-applications",
    stage: "Applications",
    skill: "Tangent gradient",
    title: "Tangent gradient",
    questionText: "Find the gradient of the tangent to $y=x^4-3x$ at $x=2$.",
    marks: 3,
    answerType: "numerical",
    correctAnswer: "29",
    acceptedAnswers: ["29"],
    workedSolution: "Differentiate:\n\n$$\\frac{dy}{dx}=4x^3-3$$\n\nAt $x=2$:\n\n$$4(2)^3-3=32-3=29$$\n\nSo the tangent gradient is 29.",
    finalAnswer: "$29$",
    hint: "The gradient of the tangent is the derivative at that $x$-value.",
    commonMistake: "A common mistake is to find the y-coordinate instead of the gradient.",
    calculatorAllowed: false,
    source: "Original STEM Forge question",
    status: "ready",
    displayOrder: 5,
  },
  {
    id: "hm-calc-diff-basic-a-003",
    subject: "Higher Maths",
    courseArea: "Calculus",
    specArea: "Differentiation",
    skillPath: "Basic differentiation",
    skillPathId: "basic-differentiation",
    stageId: "basic-diff-stage-applications",
    stage: "Applications",
    skill: "Stationary point basics",
    title: "Stationary point condition",
    questionText: "For $y=x^2-6x+4$, find the $x$-coordinate of the stationary point.",
    marks: 3,
    answerType: "numerical",
    correctAnswer: "3",
    acceptedAnswers: ["3"],
    workedSolution: "Stationary points occur when:\n\n$$\\frac{dy}{dx}=0$$\n\nDifferentiate:\n\n$$\\frac{dy}{dx}=2x-6$$\n\nSet equal to zero:\n\n$$2x-6=0 \\Rightarrow x=3$$",
    finalAnswer: "$x=3$",
    hint: "At a stationary point, the derivative is zero.",
    commonMistake: "Students sometimes solve $y=0$ instead of $\\frac{dy}{dx}=0$.",
    calculatorAllowed: false,
    source: "Original STEM Forge question",
    status: "ready",
    displayOrder: 6,
  },
  {
    id: "hm-calc-diff-basic-ppq-001",
    subject: "Higher Maths",
    courseArea: "Calculus",
    specArea: "Differentiation",
    skillPath: "Basic differentiation",
    skillPathId: "basic-differentiation",
    stageId: "basic-diff-stage-past-paper-style",
    stage: "Past Paper-style Questions",
    skill: "Exam-style differentiation",
    title: "Exam-style tangent problem",
    questionText: "The curve $y=x^3-4x+1$ has a tangent at the point where $x=2$. Find the gradient of this tangent.",
    marks: 3,
    answerType: "numerical",
    correctAnswer: "8",
    acceptedAnswers: ["8"],
    workedSolution: "Differentiate the curve:\n\n$$\\frac{dy}{dx}=3x^2-4$$\n\nSubstitute $x=2$:\n\n$$3(2)^2-4=12-4=8$$\n\nThe gradient of the tangent is 8.",
    finalAnswer: "$8$",
    hint: "Differentiate first. The derivative gives the gradient function.",
    commonMistake: "Students sometimes use the original equation to find $y$ and stop there.",
    calculatorAllowed: false,
    source: "Original STEM Forge question in the style of Higher Maths exams",
    status: "ready",
    displayOrder: 7,
  },
  {
    id: "hm-calc-diff-basic-ppq-002",
    subject: "Higher Maths",
    courseArea: "Calculus",
    specArea: "Differentiation",
    skillPath: "Basic differentiation",
    skillPathId: "basic-differentiation",
    stageId: "basic-diff-stage-past-paper-style",
    stage: "Past Paper-style Questions",
    skill: "Exam-style stationary point",
    title: "Exam-style stationary point",
    questionText: "A curve has equation $y=x^3-12x+5$. Find the positive $x$-coordinate of a stationary point.",
    marks: 4,
    answerType: "numerical",
    correctAnswer: "2",
    acceptedAnswers: ["2"],
    workedSolution: "Differentiate:\n\n$$\\frac{dy}{dx}=3x^2-12$$\n\nAt a stationary point:\n\n$$3x^2-12=0$$\n\n$$3x^2=12$$\n\n$$x^2=4$$\n\n$$x=\\pm 2$$\n\nThe positive $x$-coordinate is 2.",
    finalAnswer: "$x=2$",
    hint: "Set the derivative equal to zero and solve for $x$.",
    commonMistake: "Students may give both values when the question asks for the positive one.",
    calculatorAllowed: false,
    source: "Original STEM Forge question in the style of Higher Maths exams",
    status: "ready",
    displayOrder: 8,
  },
];





